### ISSUE TITLE
Demo 2

### ISSUE THREAD

**Issue by LERUfic** [LERUfic/AJKuis#6]
- room pakai digit yang lebih pendek (done)
- menang berdasar timestamp  jika score sama (done)
- user dapat notif menang atau kalah (done)
- timer di client (done)
- benerin tampilan pilihan abcd di pc (done)
- masukin hasil tiap game ke database (done)
- kategori ambil dari database (done)
- Tampilan admin diperbaiki {
      * CRUD (done)
      * Pakai Admin LTE
      * Kategori dibuat drop down [alternatif diberi list kategori] (done)
      * Input text di ganti jadi lebih besar (done)
}

**Comment by LERUfic** [comment]
Sudah dilakukan:
- menambah timer di client
- membetulkan tampilan a,b,c,d di pc

**Comment by LERUfic** [comment]
Sudah dilakukan:
- user dapat notif menang atau kalah (menunjukan ranking score client)

**Comment by LERUfic** [comment]
Sudah dilakukan:
- masukin hasil tiap game ke database

**Comment by khawari-md** [comment]
sudah dilakukan:

- menyederhanakan room number

- menyediakan error message jika room yang diinput user tidak tersedia

**Comment by LERUfic** [comment]
Sudah dilakukan:
- kategori ambil dari database

**Comment by LERUfic** [comment]
sudah dilakukan:
- CRUD halaman admin

**Comment by LERUfic** [comment]
Sudah dilakukan:
- input memakai textarea
